/**
 * GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json — do not edit by hand.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'simulated' stamped per class so the UI can label synthetic prices.
 */
import type { BacktestResult } from '../types';

export const backtestFixtures: BacktestResult[] = [
  {
    "lookback": "30d",
    "ret": 4.2,
    "maxDd": -2.1,
    "sharpe": 1.4,
    "trades": 18,
    "curve": "0,96 40,92 80,86 120,88 160,78 200,74 240,70 280,66 320,58 360,52"
  },
  {
    "lookback": "90d",
    "ret": 11.8,
    "maxDd": -5.4,
    "sharpe": 1.7,
    "trades": 54,
    "curve": "0,100 40,94 80,88 120,80 160,84 200,70 240,62 280,58 320,44 360,32"
  },
  {
    "lookback": "6m",
    "ret": 23.5,
    "maxDd": -9.2,
    "sharpe": 1.2,
    "trades": 121,
    "curve": "0,102 40,90 80,96 120,78 160,66 200,72 240,54 280,46 320,34 360,20"
  },
  {
    "lookback": "1y",
    "ret": 41.9,
    "maxDd": -14.6,
    "sharpe": 1.1,
    "trades": 244,
    "curve": "0,104 40,96 80,84 120,90 160,70 200,58 240,64 280,44 320,28 360,10"
  }
];
