/**
 * GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json — do not edit by hand.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'simulated' stamped per class so the UI can label synthetic prices.
 */
import type { AssetClass } from '../types';

export const assetClasses: AssetClass[] = [
  {
    "id": "crypto",
    "label": "Crypto",
    "note": "300+ coins · spot, margin, perps, options",
    "more": "See all 312 crypto markets",
    "instruments": [
      {
        "sym": "BTC",
        "name": "Bitcoin",
        "tag": "Perp · 100x",
        "px": "$66,560",
        "chg": "+0.67%",
        "up": true,
        "c1": "#F7931A",
        "c2": "#B96908",
        "classId": "crypto",
        "feed": "live",
        "mint": "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"
      },
      {
        "sym": "ETH",
        "name": "Ethereum",
        "tag": "Perp · 100x",
        "px": "$2,443",
        "chg": "+2.11%",
        "up": true,
        "c1": "#8FA6E8",
        "c2": "#4B5FA8",
        "classId": "crypto",
        "feed": "live",
        "mint": "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs"
      },
      {
        "sym": "SOL",
        "name": "Solana",
        "tag": "Spot · Perp",
        "px": "$88.32",
        "chg": "+2.40%",
        "up": true,
        "c1": "#5B93FF",
        "c2": "#49E39B",
        "classId": "crypto",
        "feed": "live",
        "mint": "So11111111111111111111111111111111111111112"
      },
      {
        "sym": "XRP",
        "name": "XRP",
        "tag": "Perp · 50x",
        "px": "$2.94",
        "chg": "−1.08%",
        "up": false,
        "c1": "#9AA3AD",
        "c2": "#4A5058",
        "classId": "crypto",
        "feed": "live",
        "mint": "Ga2AXHpqdfyDBFcefJit2Qm7GRhCPkTBQzFnkULRC2ZH"
      },
      {
        "sym": "DOGE",
        "name": "Dogecoin",
        "tag": "Perp · 50x",
        "px": "$0.1842",
        "chg": "+4.12%",
        "up": true,
        "c1": "#E0C36B",
        "c2": "#A5842A",
        "classId": "crypto",
        "feed": "live",
        "mint": "2wme8EVkw8qsfSk2B3QeX4S64ac6wxHPXb3GrdckEkio"
      },
      {
        "sym": "HYPE",
        "name": "Hyperliquid",
        "tag": "Spot · Perp",
        "px": "$40.96",
        "chg": "−1.20%",
        "up": false,
        "c1": "#49E39B",
        "c2": "#0E8F55",
        "classId": "crypto",
        "feed": "live"
      },
      {
        "sym": "AAVE",
        "name": "Aave",
        "tag": "Spot · Perp",
        "px": "$291.03",
        "chg": "+3.10%",
        "up": true,
        "c1": "#B58CFF",
        "c2": "#6E3ED8",
        "classId": "crypto",
        "feed": "live",
        "mint": "3vAs4D1WE6Na4tCgt4BApgFfENbm8WY7q4cSPD1yM4Cg"
      },
      {
        "sym": "LINK",
        "name": "Chainlink",
        "tag": "Perp · 50x",
        "px": "$18.44",
        "chg": "+1.05%",
        "up": true,
        "c1": "#5B93FF",
        "c2": "#1B44CE",
        "classId": "crypto",
        "feed": "live",
        "mint": "CWE8jPTUYhdCTZYWPTe1o5DFqfdjzWKc9WKz6rSjQUdG"
      },
      {
        "sym": "TON",
        "name": "Toncoin",
        "tag": "Spot · Perp",
        "px": "$5.21",
        "chg": "−0.36%",
        "up": false,
        "c1": "#63C3F5",
        "c2": "#1D6FA8",
        "classId": "crypto",
        "feed": "live",
        "mint": "GEYrotdkRitGUK5UMv3aMttEhVAZLhRJMcG82zKYsaWB"
      }
    ]
  },
  {
    "id": "stocks",
    "label": "Stocks",
    "note": "Tokenized shares on Base · routed through 1inch",
    "more": "See all tokenized equities",
    "instruments": [
      {
        "sym": "NVDAc",
        "name": "Nvidia",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#7CD64F",
        "c2": "#3D8B1E",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb20000000000000000000078ee7ce2fE4908108C"
      },
      {
        "sym": "AAPLc",
        "name": "Apple",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#C9CDD4",
        "c2": "#7A7F87",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb200000000000000000000C2e324d24d7eEcd1fb"
      },
      {
        "sym": "TSLAc",
        "name": "Tesla",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#E8464B",
        "c2": "#98181C",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb2000000000000000000001e800a7f5189430cD0"
      },
      {
        "sym": "METAc",
        "name": "Meta",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#5B93FF",
        "c2": "#1B44CE",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb2000000000000000000008bC8786B856E61707C"
      },
      {
        "sym": "MSFTc",
        "name": "Microsoft",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#63C3F5",
        "c2": "#1D6FA8",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xB200000000000000000000Ab99cFa739E253872B"
      },
      {
        "sym": "AMZNc",
        "name": "Amazon",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#F0BE55",
        "c2": "#B8791A",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb200000000000000000000d9192b6B456483C2E8"
      },
      {
        "sym": "GOOGLc",
        "name": "Alphabet",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#7FA9FF",
        "c2": "#2D57C4",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb2000000000000000000002D0BA3164cc74f58B7"
      },
      {
        "sym": "MSTRc",
        "name": "MicroStrategy",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#F5A05A",
        "c2": "#B0561A",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb2000000000000000000004884b426556b92883d"
      }
    ]
  },
  {
    "id": "commodities",
    "label": "Commodities",
    "note": "Perpetual swaps · no expiry · ICE feed on crude",
    "more": "See all 11 commodity contracts",
    "instruments": [
      {
        "sym": "XAUT",
        "name": "Gold",
        "tag": "Perp · spot feed",
        "px": "$3,412.10",
        "chg": "+0.44%",
        "up": true,
        "c1": "#F5CE5F",
        "c2": "#B98A0C",
        "classId": "commodities",
        "feed": "simulated"
      },
      {
        "sym": "XAGT",
        "name": "Silver",
        "tag": "Perp · spot feed",
        "px": "$38.71",
        "chg": "−0.61%",
        "up": false,
        "c1": "#D6DBE2",
        "c2": "#8C929B",
        "classId": "commodities",
        "feed": "simulated"
      },
      {
        "sym": "CL",
        "name": "WTI Crude",
        "tag": "Perp · ICE feed",
        "px": "$71.84",
        "chg": "+1.92%",
        "up": true,
        "c1": "#4A5058",
        "c2": "#1B1E22",
        "classId": "commodities",
        "feed": "simulated"
      },
      {
        "sym": "BZ",
        "name": "Brent Crude",
        "tag": "Perp · ICE feed",
        "px": "$75.30",
        "chg": "+1.66%",
        "up": true,
        "c1": "#5C6470",
        "c2": "#22262C",
        "classId": "commodities",
        "feed": "simulated"
      },
      {
        "sym": "HG",
        "name": "Copper",
        "tag": "Perp · delivery ref",
        "px": "$4.62",
        "chg": "−0.28%",
        "up": false,
        "c1": "#E08B5A",
        "c2": "#9A4E22",
        "classId": "commodities",
        "feed": "simulated"
      },
      {
        "sym": "PL",
        "name": "Platinum",
        "tag": "Perp · spot feed",
        "px": "$1,042.60",
        "chg": "+0.83%",
        "up": true,
        "c1": "#C9CDD4",
        "c2": "#7A7F87",
        "classId": "commodities",
        "feed": "simulated"
      },
      {
        "sym": "PA",
        "name": "Palladium",
        "tag": "Perp · spot feed",
        "px": "$1,118.40",
        "chg": "−1.44%",
        "up": false,
        "c1": "#B8BEC8",
        "c2": "#6A7078",
        "classId": "commodities",
        "feed": "simulated"
      },
      {
        "sym": "NG",
        "name": "Natural Gas",
        "tag": "Perp · ICE feed",
        "px": "$3.18",
        "chg": "+2.51%",
        "up": true,
        "c1": "#7FD6F5",
        "c2": "#1D7FA8",
        "classId": "commodities",
        "feed": "simulated"
      },
      {
        "sym": "ZW",
        "name": "Wheat",
        "tag": "Perp · CBOT ref",
        "px": "$5.74",
        "chg": "−0.62%",
        "up": false,
        "c1": "#E8C46B",
        "c2": "#A5822A",
        "classId": "commodities",
        "feed": "simulated"
      }
    ]
  },
  {
    "id": "indices",
    "label": "Indices",
    "note": "Index exposure through tokenized ETFs",
    "more": "See all 9 index products",
    "instruments": [
      {
        "sym": "SPYx",
        "name": "S&P 500",
        "tag": "Spot · Perp",
        "px": "$598.14",
        "chg": "+0.38%",
        "up": true,
        "c1": "#5B93FF",
        "c2": "#1B44CE",
        "classId": "indices",
        "feed": "simulated"
      },
      {
        "sym": "QQQx",
        "name": "Nasdaq 100",
        "tag": "Spot · Perp",
        "px": "$521.77",
        "chg": "+0.62%",
        "up": true,
        "c1": "#B58CFF",
        "c2": "#7A45E0",
        "classId": "indices",
        "feed": "simulated"
      },
      {
        "sym": "IWMx",
        "name": "Russell 2000",
        "tag": "Perp · 10x",
        "px": "$232.05",
        "chg": "+0.94%",
        "up": true,
        "c1": "#49E39B",
        "c2": "#12A45F",
        "classId": "indices",
        "feed": "simulated"
      },
      {
        "sym": "DIAx",
        "name": "Dow 30",
        "tag": "Perp · 10x",
        "px": "$438.12",
        "chg": "+0.21%",
        "up": true,
        "c1": "#7FA9FF",
        "c2": "#2D57C4",
        "classId": "indices",
        "feed": "simulated"
      },
      {
        "sym": "EFAx",
        "name": "MSCI EAFE",
        "tag": "Perp · 10x",
        "px": "$84.66",
        "chg": "−0.33%",
        "up": false,
        "c1": "#C9CDD4",
        "c2": "#7A7F87",
        "classId": "indices",
        "feed": "simulated"
      },
      {
        "sym": "GLDx",
        "name": "Gold ETF",
        "tag": "Spot · Perp",
        "px": "$316.44",
        "chg": "+0.41%",
        "up": true,
        "c1": "#F5CE5F",
        "c2": "#B98A0C",
        "classId": "indices",
        "feed": "simulated"
      },
      {
        "sym": "TLTx",
        "name": "20Y Treasury",
        "tag": "Perp · 10x",
        "px": "$88.90",
        "chg": "−0.72%",
        "up": false,
        "c1": "#8FA6E8",
        "c2": "#4B5FA8",
        "classId": "indices",
        "feed": "simulated"
      },
      {
        "sym": "HYGx",
        "name": "High Yield",
        "tag": "Perp · 10x",
        "px": "$79.34",
        "chg": "+0.12%",
        "up": true,
        "c1": "#E8A05A",
        "c2": "#B0561A",
        "classId": "indices",
        "feed": "simulated"
      },
      {
        "sym": "VIXx",
        "name": "Volatility",
        "tag": "Perp · 5x",
        "px": "$16.28",
        "chg": "−3.10%",
        "up": false,
        "c1": "#E8464B",
        "c2": "#98181C",
        "classId": "indices",
        "feed": "simulated"
      }
    ]
  },
  {
    "id": "preipo",
    "label": "Pre-IPO",
    "note": "Private-company exposure · settles at IPO",
    "more": "See all 12 pre-IPO perps",
    "instruments": [
      {
        "sym": "OPENAI",
        "name": "OpenAI",
        "tag": "Pre-IPO perp",
        "px": "$164.20",
        "chg": "+3.40%",
        "up": true,
        "c1": "#49E39B",
        "c2": "#12A45F",
        "classId": "preipo",
        "feed": "simulated"
      },
      {
        "sym": "ANTHRP",
        "name": "Anthropic",
        "tag": "Pre-IPO perp",
        "px": "$121.55",
        "chg": "+1.14%",
        "up": true,
        "c1": "#E8A05A",
        "c2": "#B0561A",
        "classId": "preipo",
        "feed": "simulated"
      },
      {
        "sym": "SPACEX",
        "name": "SpaceX",
        "tag": "Pre-IPO perp",
        "px": "$402.70",
        "chg": "+0.88%",
        "up": true,
        "c1": "#9AA3AD",
        "c2": "#3A4048",
        "classId": "preipo",
        "feed": "simulated"
      },
      {
        "sym": "XAI",
        "name": "xAI",
        "tag": "Pre-IPO perp",
        "px": "$74.15",
        "chg": "+5.62%",
        "up": true,
        "c1": "#C9CDD4",
        "c2": "#5A6068",
        "classId": "preipo",
        "feed": "simulated"
      },
      {
        "sym": "STRIPE",
        "name": "Stripe",
        "tag": "Pre-IPO perp",
        "px": "$98.40",
        "chg": "−0.74%",
        "up": false,
        "c1": "#8FA6E8",
        "c2": "#4B5FA8",
        "classId": "preipo",
        "feed": "simulated"
      },
      {
        "sym": "DBRK",
        "name": "Databricks",
        "tag": "Pre-IPO perp",
        "px": "$142.08",
        "chg": "+1.36%",
        "up": true,
        "c1": "#E8464B",
        "c2": "#98181C",
        "classId": "preipo",
        "feed": "simulated"
      },
      {
        "sym": "PPLX",
        "name": "Perplexity",
        "tag": "Pre-IPO perp",
        "px": "$61.92",
        "chg": "+2.05%",
        "up": true,
        "c1": "#49E39B",
        "c2": "#12A45F",
        "classId": "preipo",
        "feed": "simulated"
      },
      {
        "sym": "FIGMA",
        "name": "Figma",
        "tag": "Lists at IPO",
        "px": "—",
        "chg": "Soon",
        "up": true,
        "c1": "#B58CFF",
        "c2": "#7A45E0",
        "classId": "preipo",
        "feed": "simulated"
      },
      {
        "sym": "CANVA",
        "name": "Canva",
        "tag": "Pre-IPO perp",
        "px": "$41.20",
        "chg": "+1.35%",
        "up": true,
        "c1": "#7FD6F5",
        "c2": "#1D7FA8",
        "classId": "preipo",
        "feed": "simulated"
      }
    ]
  }
];
