/**
 * GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json — do not edit by hand.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'simulated' stamped per class so the UI can label synthetic prices.
 */
import type { Sleeve } from '../types';

export const sleeveFixtures: Sleeve[] = [
  {
    "name": "Blue-chip crypto",
    "weight": 55,
    "note": "BTC, ETH, SOL — the liquid core the agent rebalances weekly.",
    "color": "#5B93FF"
  },
  {
    "name": "Tokenized equities",
    "weight": 30,
    "note": "NVDAx, AAPLx. Tracks earnings dates and gaps out before prints.",
    "color": "#F0BE55"
  },
  {
    "name": "Stable yield",
    "weight": 15,
    "note": "Staked SOL and T-bill tokens. Funds the agent's dry powder.",
    "color": "#49E39B"
  }
];
